import pygame

GAME_TITLE = 'Jeu'

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = (720, 540)
BACKGROUND = '#d8dcb4'

# KEYS
KEY_PLAYER_DOWN = pygame.K_s
KEY_PLAYER_UP = pygame.K_z
KEY_PLAYER_LEFT = pygame.K_q
KEY_PLAYER_RIGHT = pygame.K_d
KEY_PLAYER_ATTACK = pygame.K_SPACE

KEY_INVENTORY_RIGHT = pygame.K_RIGHT
KEY_INVENTORY_LEFT = pygame.K_LEFT

# PLAYER
PLAYER_SIZE = PLAYER_WIDTH, PLAYER_HEIGHT = (32, 32)
PLAYER_COLOR = (255, 0, 0)
PLAYER_SPEED = 200
